import pandas as pd


class PlayerList:

    def __init__(self, player_file):
        self.players = []

        player_df = pd.read_csv(player_file)

        for index, row in player_df.iterrows():
            new_player = f'{row.First}%20{row.Last}'
            self.players.append(new_player)










# players = [
#     "Brandon%20Allen", "Josh%20Allen", "Kyle%20Allen", "Matt%20Barkley", "C.J.%20Beathard", "David%20Blough",
#     "Ian%20Book", "Tim%20Boyle", "Tom%20Brady", "Teddy%20Bridgewater", "Jacoby%20Brissett", "Anthony%20Brown",
#     "Jake%20Browning", "Shane%20Buechele", "Joe%20Burrow", "Derek%20Carr", "Jack%20Coan", "Kirk%20Cousins",
#     "Dustin%20Crum", "Andy%20Dalton", "Chase%20Daniel", "Sam%20Darnold", "Ben%20DiNucci", "Joshua%20Dobbs",
#     "Jeff%20Driskel", "Jacob%20Eason", "Sam%20Ehlinger", "Danny%20Etling", "Justin%20Fields", "Joe%20Flacco",
#     "Nick%20Foles", "Feleipe%20Franks", "Blaine%20Gabbert", "Chase%20Garbers", "Jimmy%20Garoppolo", "Jared%20Goff",
#     "Will%20Grier", "Ryan%20Griffin", "Jarrett%20Guarantano", "Dwayne%20Haskins", "Taylor%20Heinicke", "Chad%20Henne",
#     "Justin%20Herbert", "Taysom%20Hill", "Kevin%20Hogan", "Sam%20Howell", "Brian%20Hoyer", "Brett%20Hundley",
#     "Tyler%20Huntley", "Jalen%20Hurts", "Lamar%20Jackson", "Josh%20Johnson", "Daniel%20Jones", "Mac%20Jones",
#     "Case%20Keenum", "Cole%20Kelley", "Trey%20Lance", "Trevor%20Lawrence", "Drew%20Lock", "Jordan%20Love",
#     "Jake%20Luton", "Patrick%20Mahomes", "Sean%20Mannion", "Marcus%20Mariota", "Baker%20Mayfield", "Colt%20McCoy",
#     "Trace%20McSorley", "Davis%20Mills", "Gardner%20Minshew", "Kellen%20Mond", "Nick%20Mullens", "Kyler%20Murray",
#     "Chris%20Oladokun", "Bryce%20Perkins", "E.J.%20Perry", "Nathan%20Peterman", "Brandon%20Peters", "Kenny%20Pickett",
#     "Dak%20Prescott", "Brock%20Purdy", "Aaron%20Rodgers", "Mason%20Rudolph", "Cooper%20Rush", "Matt%20Ryan",
#     "Brett%20Rypien", "Trevor%20Siemian", "Reid%20Sinnett", "Geno%20Smith", "Matthew%20Stafford", "Nathan%20Stanley",
#     "Easton%20Stick", "Jarrett%20Stidham", "Carson%20Strong", "Nate%20Sudfeld", "Tua%20Tagovailoa", "Ryan%20Tannehill",
#     "Tyrod%20Taylor", "Skylar%20Thompson", "Kyle%20Trask", "Mitchell%20Trubisky", "Phillip%20Walker",
#     "Deshaun%20Watson", "Davis%20Webb", "Carson%20Wentz", "Mike%20White", "Russell%20Wilson", "Zach%20Wilson",
#     "Jameis%20Winston", "John%20Wolford", "Logan%20Woodside", "Bailey%20Zappe", "Ameer%20Abdullah", "Salvon%20Ahmed",
#     "Cam%20Akers", "Tyler%20Allgeier", "Darius%20Anderson", "Alex%20Armah", "Ryquell%20Armstead", "Tyler%20Badie",
#     "Jake%20Bargas", "Saquon%20Barkley", "Kenjon%20Barner", "Nick%20Bawden", "B.J.%20Baylor", "Andrew%20Beck",
#     "Greg%20Bell", "Eno%20Benjamin", "Giovani%20Bernard", "Raheem%20Blackshear", "Khari%20Blasingame",
#     "Brandon%20Bolden", "Reggie%20Bonnafon", "Mike%20Boone", "Darius%20Bradwell", "Matt%20Breida", "Gary%20Brightwell",
#     "Kennedy%20Brooks", "Brittain%20Brown", "Leddie%20Brown", "Spencer%20Brown", "Rex%20Burkhead", "Michael%20Burton",
#     "Jason%20Cabinda", "Raymond%20Calais", "Trenton%20Cannon", "Chris%20Carson", "Michael%20Carter", "Tory%20Carter",
#     "Ty%20Chandler", "Julius%20Chestnut", "Nick%20Chubb", "Tevin%20Coleman", "James%20Conner", "Snoop%20Conner",
#     "Dalvin%20Cook", "James%20Cook", "Jashaun%20Corbin", "Nate%20Cottrell", "Damarea%20Crockett", "DeeJay%20Dallas",
#     "Malik%20Davis", "Mike%20Davis", "Tyrion%20Davis-Price", "AJ%20Dillon", "Gerrid%20Doaks", "J.K.%20Dobbins",
#     "Rico%20Dowdle", "Kenyan%20Drake", "Mataeo%20Durant", "Jerrion%20Ealy", "Trestan%20Ebner", "Chase%20Edmonds",
#     "Trey%20Edmunds", "Gus%20Edwards", "Clyde%20Edwards-Helaire", "Austin%20Ekeler", "Ezekiel%20Elliott",
#     "Travis%20Etienne", "Chris%20Evans", "Darrynton%20Evans", "Demetric%20Felton", "Tayon%20Fleet-Davis",
#     "Jerome%20Ford", "D'Onta%20Foreman", "Leonard%20Fournette", "Royce%20Freeman", "Jake%20Funk", "Kenny%20Gainwell",
#     "Myles%20Gaskin", "Antonio%20Gibson", "Reggie%20Gilliam", "Tyler%20Goodson", "Melvin%20Gordon", "Derrick%20Gore",
#     "Jeremiah%20Hall", "C.J.%20Ham", "Damien%20Harris", "Kevin%20Harris", "Najee%20Harris", "Hassan%20Haskins",
#     "JaMycal%20Hasty", "Darrell%20Henderson", "Derrick%20Henry", "Khalil%20Herbert", "Justice%20Hill", "Kylin%20Hill",
#     "Dontrell%20Hilliard", "Nyheim%20Hines", "Josh%20Hokit", "Elijah%20Holyfield", "Travis%20Homer",
#     "Alexander%20Horvath", "Chuba%20Hubbard", "Kareem%20Hunt", "Caleb%20Huntley", "Jason%20Huntley",
#     "Godwin%20Igwebuike", "Alec%20Ingold", "Keaontay%20Ingram", "Mark%20Ingram", "Deon%20Jackson", "Josh%20Jacobs",
#     "Andy%20Janovich", "Jermar%20Jefferson", "D'Ernest%20Johnson", "Duke%20Johnson", "Jakob%20Johnson",
#     "Josh%20Johnson", "Ty%20Johnson", "Aaron%20Jones", "Ronald%20Jones II", "Shermari%20Jones", "Taiwan%20Jones",
#     "Tony%20Jones", "Xavier%20Jones", "Kyle%20Juszczyk", "Alvin%20Kamara", "Joshua%20Kelley", "John%20Kelly",
#     "Zonovan%20Knight", "Bryant%20Koback", "Phillip%20Lindsay", "John%20Lovett", "John%20Lovett", "Marlon%20Mack",
#     "Kevin%20Marks", "Jordan%20Mason", "Alexander%20Mattison", "Tyreik%20McAllister", "Christian%20McCaffrey",
#     "Sincere%20McCormick", "Nate%20McCrary", "Anthony%20McFarland", "Jerick%20McKinnon", "J.D.%20McKissic",
#     "Sony%20Michel", "Elijah%20Mitchell", "Joe%20Mixon", "David%20Montgomery", "Zack%20Moss", "Raheem%20Mostert",
#     "Gabe%20Nabers", "Ryan%20Nall", "Kene%20Nwangwu", "Dare%20Ogunbowale", "Qadree%20Ollison", "Devine%20Ozigbo",
#     "Isiah%20Pacheco", "Cordarrelle%20Patterson", "Jaret%20Patterson", "Rashaad%20Penny", "Lamical%20Perine",
#     "Samaje%20Perine", "Ricky%20Person", "Dameon%20Pierce", "Sandro%20Platzgummer", "T.J.%20Pledger", "Tony%20Pollard",
#     "Adam%20Prentice", "D'Vonte%20Price", "Paul%20Quessenberry", "Nick%20Ralston", "Craig%20Reynolds",
#     "Patrick%20Ricard", "Giovanni%20Ricci", "Ronnie%20Rivers", "Brian%20Robinson", "James%20Robinson", "A.J.%20Rose",
#     "Larry%20Rountree", "Miles%20Sanders", "Mekhi%20Sargent", "Boston%20Scott", "Trey%20Sermon", "Aaron%20Shampklin",
#     "Devin%20Singletary", "Abram%20Smith", "Keith%20Smith", "Benjamin%20Snell", "Isaiah%20Spiller", "Johnny%20Stanton",
#     "Rhamondre%20Stevenson", "Pierre%20Strong", "D'Andre%20Swift", "J.J.%20Taylor", "Jonathan%20Taylor",
#     "Patrick%20Taylor", "Darwin%20Thompson", "De'Montre%20Tuggle", "Ke'Shawn%20Vaughn", "CJ%20Verdell",
#     "Jonathan%20Ward", "Jaylen%20Warren", "Dwayne%20Washington", "Derek%20Watt", "James%20White", "Rachaad%20White",
#     "Zamir%20White", "Zaquandre%20White", "Jordan%20Wilkins", "Antonio%20Williams", "Avery%20Williams",
#     "Damien%20Williams", "Darrel%20Williams", "Jamaal%20Williams", "Javonte%20Williams", "Jonathan%20Williams",
#     "Kyren%20Williams", "Trayveon%20Williams", "Ty'Son%20Williams", "Jeffery%20Wilson", "Keshunn%20Abram",
#     "Davante%20Adams", "Rodney%20Adams", "Nelson%20Agholor", "Jamal%20Agnew", "Brandon%20Aiyuk", "Landen%20Akers",
#     "Deontez%20Alexander", "Devon%20Allen", "Keenan%20Allen", "Geronimo%20Allison", "Robby%20Anderson",
#     "Chatarius%20Atwell", "Calvin%20Austin", "Kevin%20Austin", "Tavon%20Austin", "Andre%20Baccellia", "Alex%20Bachman",
#     "Kawaan%20Baker", "Michael%20Bandy", "Rashod%20Bateman", "Cameron%20Batson", "Omar%20Bayless", "Chad%20Beebe",
#     "David%20Bell", "Trinity%20Benson", "Jared%20Bernhardt", "Braxton%20Berrios", "Stanley%20Berryhill",
#     "Tarik%20Black", "Christian%20Blake", "C.J.%20Board", "Slade%20Bolden", "Kendrick%20Bourne", "Lynn%20Bowden",
#     "Tyler%20Boyd", "Miles%20Boykin", "Trevon%20Bradford", "Ja'Marcus%20Bradley", "Shemar%20Bridges", "A.J.%20Brown",
#     "Dyami%20Brown", "Kameron%20Brown", "Marquise%20Brown", "Noah%20Brown", "Treylon%20Burks", "Damiere%20Byrd",
#     "Deon%20Cain", "Marquez%20Callaway", "Jalen%20Camp", "Parris%20Campbell", "DeAndre%20Carter", "Quintez%20Cephus",
#     "D.J.%20Chark", "Irvin%20Charles", "Ja'Marr%20Chase", "Dan%20Chisena", "Trevon%20Clark", "Chase%20Claypool",
#     "Tyrie%20Cleveland", "Randall%20Cobb", "Keelan%20Cole", "Corey%20Coleman", "Nico%20Collins", "Chris%20Conley",
#     "Brandin%20Cooks", "Amari%20Cooper", "Cody%20Core", "Jeff%20Cotton", "Isaiah%20Coulter", "Keke%20Coutee",
#     "Britain%20Covey", "River%20Cracraft", "Kekoa%20Crawford", "Jamison%20Crowder", "Frank%20Darby", "Jaelon%20Darden",
#     "Corey%20Davis", "Danny%20Davis", "Davion%20Davis", "Gabriel%20Davis", "Kaden%20Davis", "Devonte%20Dedmon",
#     "Stefon%20Diggs", "Dai'Jean%20Dixon", "Phillip%20Dorsett", "Greg%20Dortch", "Keelan%20Doss", "Jahan%20Dotson",
#     "Romeo%20Doubs", "Dontario%20Drummond", "Ashton%20Dulin", "Devin%20Duvernay", "Bryan%20Edwards", "Alex%20Erickson",
#     "D'Wayne%20Eskridge", "Drew%20Estrada", "Mike%20Evans", "Erik%20Ezukanma", "Jequez%20Ezzard", "Simi%20Fehoko",
#     "Ethan%20Fernea", "Maurice%20Ffrench", "Chris%20Finke", "Dez%20Fitzpatrick", "Robert%20Foster",
#     "Daurice%20Fountain", "Ty%20Fryfogle", "Travis%20Fulgham", "Aaron%20Fuller", "Russell%20Gage", "Michael%20Gallup",
#     "Kaylon%20Geiger", "Tanner%20Gentry", "Chris%20Godwin", "Kenny%20Golladay", "Marquise%20Goodwin", "Josh%20Gordon",
#     "Jakeem%20Grant", "Danny%20Gray", "Cyril%20Grayson", "A.J.%20Green", "Juwan%20Green", "Jalen%20Guyton",
#     "Justin%20Hall", "Marvin%20Hall", "KJ%20Hamler", "Josh%20Hammond", "Mecole%20Hardman", "Mike%20Harley",
#     "Kelvin%20Harmon", "DeMichael%20Harris", "Deonte%20Harris", "Travell%20Harris", "N'Keal%20Harry", "Penny%20Hart",
#     "Jaivon%20Heiligh", "Thomas%20Hennigan", "Ra'shaun%20Henry", "Rashard%20Higgins", "Tee%20Higgins",
#     "John%20Hightower", "Tyreek%20Hill", "Kendall%20Hinton", "Khadarel%20Hodge", "Isaiah%20Hodgins", "Mack%20Hollins",
#     "Cody%20Hollister", "DeAndre%20Hopkins", "Dennis%20Houston", "Lil'Jordan%20Humphrey", "Trenton%20Irwin",
#     "Andy%20Isabella", "Calvin%20Jackson", "Trishton%20Jackson", "Warren%20Jackson", "Richie%20James",
#     "Tyshaun%20James", "Justin%20Jefferson", "Van%20Jefferson", "Gary%20Jennings", "Jauan%20Jennings", "Jerry%20Jeudy",
#     "Brandon%20Johnson", "Cade%20Johnson", "Collin%20Johnson", "Diontae%20Johnson", "Johnny%20Johnson",
#     "Joshua%20Johnson", "KeeSean%20Johnson", "Marcus%20Johnson", "Olabisi%20Johnson", "Tyler%20Johnson",
#     "Tyron%20Johnson", "Willie%20Johnson", "Marvin%20Jones", "Tim%20Jones", "Velus%20Jones", "Zay%20Jones",
#     "Kevin%20Kassis", "Tom%20Kennedy", "Mason%20Kinsey", "Christian%20Kirk", "Jontre%20Kirklin", "Keith%20Kirkwood",
#     "J.J.%20Koski", "Jake%20Kumerow", "Cooper%20Kupp", "CeeDee%20Lamb", "Jarvis%20Landry", "Kwamie%20Lassiter",
#     "Allen%20Lazard", "Brandon%20Lewis", "Tyler%20Lockett", "Drake%20London", "Austin%20Mack", "Taysir%20Mack",
#     "Josh%20Malone", "Terrace%20Marshall", "Tay%20Martin", "Ray Ray%20McCloud", "Lance%20McCutcheon", "Ryan%20McDaniel",
#     "Kyric%20McGowan", "Isaiah%20McKenzie", "Terry%20McLaurin", "Racey%20McMath", "Bo%20Melton", "Kirk%20Merritt",
#     "D.K.%20Metcalf", "John%20Metchie", "Jakobi%20Meyers", "Marken%20Michel", "Anthony%20Miller", "Scott%20Miller",
#     "Dax%20Milne", "Denzel%20Mims", "Myron%20Mitchell", "D.J.%20Montgomery", "Ty%20Montgomery", "Darnell%20Mooney",
#     "Chris%20Moore", "D.J.%20Moore", "David%20Moore", "Elijah%20Moore", "Jason%20Moore", "Jaylon%20Moore",
#     "Rondale%20Moore", "Skyy%20Moore", "Stanley%20Morgan", "Samson%20Nacua", "Jalen%20Nailor", "Dazz%20Newsome",
#     "Tre%20Nixon", "Chris%20Olave", "Gunner%20Olszewski", "K.J.%20Osborn", "Josh%20Palmer", "Andrew%20Parchment",
#     "Aaron%20Parker", "DeVante%20Parker", "Zach%20Pascal", "Dezmon%20Patmon", "Tim%20Patrick", "Neil%20Pau'u",
#     "JaVonta%20Payton", "Donovan%20Peoples-Jones", "Breshad%20Perriman", "Malcolm%20Perry", "Dante%20Pettis",
#     "Kyle%20Philips", "George%20Pickens", "Alec%20Pierce", "Kalil%20Pimpleton", "Michael%20Pittman", "Makai%20Polk",
#     "Brandon%20Powell", "Cornell%20Powell", "Byron%20Pringle", "James%20Proche", "Austin%20Proehl", "Blake%20Proehl",
#     "Kendric%20Pryor", "Trey%20Quinn", "Charleston%20Rambo", "Kalif%20Raymond", "Jalen%20Reagor", "Joe%20Reed",
#     "Hunter%20Renfrow", "Josh%20Reynolds", "Calvin%20Ridley", "Jaquarii%20Roberson", "Reggie%20Roberson",
#     "Andre%20Roberts", "Allen%20Robinson", "Demarcus%20Robinson", "Amari%20Rodgers", "Justyn%20Ross", "Henry%20Ruggs",
#     "Curtis%20Samuel", "Deebo%20Samuel", "Braylon%20Sanders", "C.J.%20Saunders", "Anthony%20Schwartz",
#     "Mathew%20Sexton", "Kevin%20Shaa", "Rashid%20Shaheed", "Khalil%20Shakir", "Tajae%20Sharpe", "Laviska%20Shenault",
#     "Sterling%20Shepard", "Trent%20Sherfield", "David%20Sills", "Cam%20Sims", "Steven%20Sims", "Bennett%20Skowronek",
#     "Matt%20Slater", "Darius%20Slayton", "Jared%20Smart", "Brandon%20Smith", "DeVonta%20Smith", "Jeff%20Smith",
#     "Shi%20Smith", "Tre'Quan%20Smith", "Vyncint%20Smith", "Ihmir%20Smith-Marsette", "JuJu%20Smith-Schuster",
#     "Tyler%20Snead", "Jack%20Sorenson", "Amon-Ra%20St. Brown", "Equanimeous%20St. Brown", "Jerreth%20Sterns",
#     "Marquez%20Stevenson", "Dillon%20Stoner", "Mike%20Strachan", "Corey%20Sutton", "Courtland%20Sutton",
#     "Freddie%20Swain", "Auden%20Tate", "Malik%20Taylor", "Trent%20Taylor", "Adam%20Thielen", "Michael%20Thomas",
#     "Mike%20Thomas", "Deven%20Thompkins", "Cody%20Thompson", "Tyquan%20Thornton", "Travis%20Toivonen",
#     "Jalen%20Tolbert", "Kadarius%20Toney", "Samori%20Toure", "Laquon%20Treadwell", "D.J.%20Turner", "Malik%20Turner",
#     "Marquez%20Valdes-Scantling", "T.J.%20Vasher", "Tyler%20Vaughns", "Jordan%20Veasy", "Binjimen%20Victor",
#     "Jalen%20Virgil", "Jaylen%20Waddle", "Tylan%20Wallace", "Greg%20Ward", "James%20Washington",
#     "Montrell%20Washington", "Quez%20Watkins", "Sammy%20Watkins", "Raleigh%20Webb", "Nsimba%20Webster",
#     "Connor%20Wedington", "Antoine%20Wesley", "Nick%20Westbrook", "Isaiah%20Weston", "Keric%20Wheatfall",
#     "Cody%20White", "Kevin%20White", "Kristian%20Wilkerson", "Devon%20Williams", "Jameson%20Williams",
#     "Mike%20Williams", "Pooka%20Williams", "Preston%20Williams", "Seth%20Williams", "Albert%20Wilson",
#     "Cedrick%20Wilson", "Garrett%20Wilson", "Javon%20Wims", "Juwann%20Winfree", "Lujuan%20Winningham",
#     "Easop%20Winston", "Michael%20Woods", "Robert%20Woods", "Derek%20Wright", "Dareke%20Young", "Michael%20Young",
#     "Olamide%20Zaccheaus", "Brandon%20Zylstra", "Jordan%20Akins", "Mo%20Alie-Cox", "Austin%20Allen", "Chase%20Allen",
#     "Stephen%20Anderson", "Mark%20Andrews", "J.J.%20Arcega-Whiteside", "Dan%20Arnold", "Devin%20Asiasi",
#     "Antony%20Auclair", "Josh%20Babicz", "John%20Bates", "Ben%20Beise", "Blake%20Bell", "Daniel%20Bellinger",
#     "Kendall%20Blanton", "Naz%20Bohannon", "Nick%20Bowers", "Nick%20Boyle", "Cameron%20Brate", "Cade%20Brewer",
#     "Pharaoh%20Brown", "Harrison%20Bryant", "Ian%20Bunting", "Matt%20Bushman", "Lawrence%20Cager", "Grant%20Calcaterra",
#     "Cethan%20Carter", "Roger%20Carter", "Tyler%20Conklin", "Tanner%20Conner", "Dominique%20Dafney", "Zach%20Davidson",
#     "Tyler%20Davis", "Derrick%20Deese", "Josiah%20Deguara", "Brandon%20Dillon", "Will%20Dissly", "Greg%20Dulcich",
#     "Ross%20Dwelley", "Ben%20Ellefson", "Alex%20Ellis", "Evan%20Engram", "Zach%20Ertz", "Nick%20Eubanks",
#     "Gerald%20Everett", "Noah%20Fant", "Luke%20Farrell", "Jake%20Ferguson", "Anthony%20Firkser", "Tucker%20Fisk",
#     "John%20FitzPatrick", "Miller%20Forristall", "Joe%20Fortson", "Cole%20Fotheringham", "Jordan%20Franks",
#     "Pat%20Freiermuth", "Troy%20Fumagalli", "Devin%20Funchess", "Antonio%20Gandy-Golden", "Zach%20Gentry",
#     "Mike%20Gesicki", "Nolan%20Givan", "Dallas%20Goedert", "Kylen%20Granson", "Noah%20Gray", "Seth%20Green",
#     "Garrett%20Griffin", "Ryan%20Griffin", "Nakia%20Griffin-Stewart", "Grayson%20Gunter", "Jacob%20Harris",
#     "Peyton%20Hendershot", "Hunter%20Henry", "Parker%20Hesse", "Connor%20Heyward", "Tyler%20Higbee", "T.J.%20Hockenson",
#     "Curtis%20Hodges", "Jacob%20Hollister", "J.P.%20Holtz", "Austin%20Hooper", "Brycen%20Hopkins", "Jesper%20Horsted",
#     "O.J.%20Howard", "JJ%20Howland", "Tanner%20Hudson", "Tommy%20Hudson", "Hayden%20Hurst", "Tyree%20Jackson",
#     "Michael%20Jacobson", "Rysen%20John", "Juwan%20Johnson", "Brevin%20Jordan", "Nikola%20Kalinic",
#     "Hunter%20Kampmoyer", "Dalton%20Keene", "Travis%20Kelce", "Ko%20Kieft", "George%20Kittle", "Cole%20Kmet",
#     "Dawson%20Knox", "Charlie%20Kolar", "Tyler%20Kroft", "Erik%20Krommenhoek", "Lucas%20Krull", "Brayden%20Lenius",
#     "Marcedes%20Lewis", "Isaiah%20Likely", "Hunter%20Long", "Tyler%20Mabry", "Alizé%20Mack", "Chris%20Manhertz",
#     "Kyle%20Markway", "Ben%20Mason", "Jordan%20Matthews", "Trey%20McBride", "Codey%20McElroy", "Sean%20McKeon",
#     "Tre'%20McKitty", "Andre%20Miller", "James%20Mitchell", "Zaire%20Mitchell-Paden", "Briley%20Moore",
#     "Foster%20Moreau", "Quintin%20Morris", "Thaddeus%20Moss", "John%20Mundt", "Nick%20Muse", "Chris%20Myarick",
#     "David%20Njoku", "James%20O'Shaughnessy", "Thomas%20Odukoya", "Andrew%20Ogletree", "Chigoziem%20Okonkwo",
#     "Albert%20Okwuegbunam", "Josh%20Oliver", "Donald%20Parham", "Dylan%20Parham", "Colby%20Parkinson",
#     "Jamal%20Pettigrew", "Chris%20Pierce", "Jared%20Pinkney", "Kyle%20Pitts", "Tony%20Poljan", "Gerrit%20Prince",
#     "Teagan%20Quitoriano", "Kevin%20Rader", "John%20Raine", "Sammis%20Reyes", "Justin%20Rigg", "Richard%20Rodgers",
#     "Armani%20Rogers", "Jeremy%20Ruckert", "Drew%20Sample", "Marcus%20Santos-Silva", "Eric%20Saubert",
#     "Mason%20Schreck", "Dalton%20Schultz", "Jared%20Scott", "Ricky%20Seals-Jones", "Bernhard%20Seikovits",
#     "Adam%20Shaheen", "Stone%20Smartt", "Irv%20Smith", "Jonnu%20Smith", "Durham%20Smythe", "Dylan%20Soehner",
#     "Matt%20Sokol", "Jeremy%20Sprinkle", "Jace%20Sternberger", "Jack%20Stoll", "Stephen%20Sullivan", "Geoff%20Swaim",
#     "Tommy%20Sweeney", "Ian%20Thomas", "Logan%20Thomas", "Colin%20Thompson", "Noah%20Togiai", "Eric%20Tomlinson",
#     "Jake%20Tonges", "Robert%20Tonyan", "Adam%20Trautman", "Tommy%20Tremble", "Cole%20Turner", "C.J.%20Uzomah",
#     "Nick%20Vannett", "Mark%20Vital", "Darren%20Waller", "Scotty%20Washington", "Leroy%20Watson", "David%20Wells",
#     "Trevon%20Wesco", "Mitchell%20Wilcox", "Maxx%20Williams", "Rodney%20Williams", "Charlie%20Woerner", "Eli%20Wolf",
#     "Jelani%20Woods", "Brock%20Wright", "Jalen%20Wydermyer", "Kenny%20Yeboah", "Deon%20Yelder", "Shane%20Zylstra",
#     "Tyler%20Bass", "Rodrigo%20Blankenship", "Jose%20Borregales", "Chris%20Boswell", "Gabe%20Brkic", "Randy%20Bullock",
#     "Harrison%20Butker", "Daniel%20Carlson", "Mason%20Crosby", "Jake%20Elliott", "Ka'imi%20Fairbairn", "Nick%20Folk",
#     "Graham%20Gano", "Jonathan%20Garibay", "Matt%20Gay", "Zane%20Gonzalez", "Robbie%20Gould", "Lirim%20Hajrullahu",
#     "Dustin%20Hopkins", "Greg%20Joseph", "Younghoe%20Koo", "Wil%20Lutz", "James%20McCourt", "Brandon%20McManus",
#     "Evan%20McPherson", "Andrew%20Mevis", "Jason%20Myers", "Quinn%20Nordin", "Riley%20Patterson", "Eddy%20Pineiro",
#     "Matt%20Prater", "John Parker%20Romo", "Jason%20Sanders", "Cairo%20Santos", "Ryan%20Santoso", "Nick%20Sciba",
#     "Austin%20Seibert", "Caleb%20Shudak", "Joey%20Slye", "Ryan%20Succop", "Justin%20Tucker", "Jake%20Verity",
#     "Tristan%20Vizcaino", "Cade%20York", "Greg%20Zuerlein"
# ]
